mindmap
    root((Central Topic))
        Branch 1
            Sub-topic 1a
            Sub-topic 1b
        Branch 2
            Sub-topic 2a
            Sub-topic 2b
        Branch 3
            Sub-topic 3a
